### ISSUE TITLE
캐릭터(강아지) 상태 아이콘

### ISSUE THREAD

**Issue by kimalec** [dadafactory/hellp#5]
각 상태 및 사이드 이미지를 압축해서 올려주세요.
단 파일명을 룰을 가지고 소문자, 숫자, _ 를 사용해서 이름 지어주세요.

**Comment by daadada95** [comment]
[chrt.zip](https://github.com/dadafactory/hellp/files/1122998/chrt.zip)

기본캐릭터랑 단계별로 변하는 캐릭터 파일이예요. 폴더안에 파일명 관련 설명도 넣어놨어요 !

**Comment by daadada95** [comment]
[img.zip](https://github.com/dadafactory/hellp/files/1123000/img.zip)

사이드 이미지가 뭔지 정확히 몰라서 기타 물품같은 자잘한 이미지 압축해놓은 거예요 !

**Comment by daadada95** [comment]
사이드 이미지가 무엇인지 잘 모르겠어요 ㅠㅠ 어떤건가요 ?

**Comment by hwanjjang** [comment]
강아지 옆모습 ㅎㅎ;

**Comment by daadada95** [comment]
아 ㅎㅎ..옆모습도 있어요..
